site_name: laravel livewire dataview
site_url: https://aristonis.github.io/laravel-livewire-dataview-docs/
repo_url: https://github.com/aristonis/laravel-livewire-dataview
repo_name: aristonis/laravel-livewire-dataview

theme:
  name: material
  i18n: true
  logo: false
  palette:
    # Light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - content.code.copy
    - search.suggest
    - search.highlight
  icon:
    language: material/translate
    repo: fontawesome/brands/github
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/aristonis/laravel-livewire-dataview
    - icon: fontawesome/solid/box
      link: https://packagist.org/packages/aristonis/laravel-livewire-dataview
    - icon: fontawesome/solid/rocket
      link: /en/3_quickStart/
  footer:
    copyright: Copyright &copy; 2025 aristonis

plugins:
  - search
  # Ensure you have 'pip install mkdocs-static-i18n' installed
  - i18n:
      docs_structure: folder
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      default_language_only: false
      languages:
        - name: English
          locale: en
          build: true
          default: true
        - name: العربية
          locale: ar
          build: true

extra:
  # This configuration connects to the 'versions.json' file generated by mike
  version:
    provider: mike
    default: latest

  # Language switcher configuration
  # Note: mkdocs-static-i18n will automatically handle language switching with version paths
  # when reconfigure_material is set to true

  # Footer customization
  generator: false

  # Footer social links (appears in footer)
  social:
    - icon: fontawesome/solid/globe
      link: https://aristonis.org
      name: Website
    - icon: fontawesome/brands/github
      link: https://github.com/aristonis/laravel-livewire-dataview
      name: GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/aristonis/
      name: LinkedIn
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/profile.php?id=61581050347135
      name: Facebook
    - icon: fontawesome/solid/envelope
      link: mailto:aristonis@outlook.com
      name: Email

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed
  - admonition
